config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'

  resources :offers
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  default_scope -> { order(created_at: :desc) }

  def self.search(query)
    if query.nil?
      all
    else
      db_query = query.split(' ').join(' & ')
      where("to_tsvector(job_title || ' ' || job_summary || ' ' || locations) \
      @@ to_tsquery('#{db_query}')")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.search(params[:query]).paginate(page: params[:page],
                                                    per_page: 20)
    @query = params[:query]
  end

  def show
    @offer = Offer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1>All jobs, in one place</h1>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag offers_path, method: 'get', class: 'form-group' do %>
      <%= label_tag 'query', 'Search by job title, keywords, location...' %>
      <%= search_field_tag 'query', '', class: 'form-control' %>
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
    <% end %>
  </div>

  <div class="col-md-10 col-md-offset-1">
    <% if @query.nil? %>
      <h2>Our latests job offers</h2>
    <% else %>
      <h2>Results for <%= @query %></h2>
    <% end %>
    <ul class="list-group">
      <% @offers.each do |offer| %>
        <li class="list-group-item">
          <span class="badge">
            Posted
            <%= distance_of_time_in_words(offer.created_at, Time.zone.now) %>
            ago
          </span>
          <h4 class="list-group-item-heading">
            <%= link_to offer.job_title, offer %>
          </h4>
          <p class="list-group-item-text">
            <%= offer.organization_name %>
          </p>
        </li>
      <% end %>
    </ul>
    <%= will_paginate @offers %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1><%= @offer.job_title %>
      <span class="badge">
        Posted
        <%= distance_of_time_in_words(@offer.created_at, Time.zone.now) %>
        ago
      </span>
    </h1>
    <h3>
      <%= @offer.organization_name %>, <%= @offer.agency_sub_element %> -
      <%= @offer.locations %>
    </h3>
    <p>
      <b>Minimum salary:</b> <%= @offer.salary_min %> |
      <b>Maximum salary:</b> <%= @offer.salary_max %> |
      <b>Salary basis:</b> <%= @offer.salary_basis %> |
      <b>Pay plan:</b> <%= @offer.pay_plan %>
    </p>
    <p>
      <b>Start date:</b> <%= @offer.start_date %> |
      <b>End date:</b> <%= @offer.end_date %>
    </p>
    <p>
      <b>Who may apply:</b> <%= @offer.who_may_apply_text %>
    </p>
    <p>
      <b>Series:</b> <%= @offer.series %> | Grade: <%= @offer.grade %>
    </p>
    <p>
      <b>Work schedule:</b> <%= @offer.work_schedule %>
    </p>
    <p>
      <b>Work type:</b> <%= @offer.work_type %>
    </p>
    <p>
      <b>Announcement number:</b> <%= @offer.announcement_number %>
    </p>
    <p>
      <%= @offer.job_summary %>
    </p>
    <%= link_to 'Apply online', @offer.apply_online_url, class: 'btn btn-primary' %>
  </div>
</div>